name: cmake
on:
  pull_request:
    branches: ["master"]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: List Qt modueles
      continue-on-error: true
      run: qmake --version

    - name: Create build environment
      # Cmake file does not allow in source build
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Build your program with the given configuration
      run: cmake --build . --config ${{env.BUILD_TYPE}}
